version: "3.1"
services:
  db:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: intadmin
      MYSQL_PASSWORD: Charito2020
      MYSQL_ROOT_PASSWORD: Charito2020
    ports:
      - 3309:3306